# Generated by Django 5.0.6 on 2024-07-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Заголовок поста",
                        max_length=150,
                        verbose_name="Заголовок",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=150, unique=True)),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Содержание поста",
                        null=True,
                        verbose_name="Содержание",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Превью изображения поста",
                        null=True,
                        upload_to="blog/photo",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="Опубликован"
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(default=0, verbose_name="Просмотры"),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
