# Generated by Django 4.2.2 on 2024-08-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category"],
                "permissions": [
                    ("can_cancel_publication", "Can cancel publication of product"),
                    ("can_change_description", "Can change description of product"),
                    ("can_change_product_category", "Can change product category"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
